ncloudcamp16-team3/ncamp16-team3-front

package-lock.json, src/components/User/ReqUi.jsx, src/components/User/RequiUi.jsx, src/components/User/Step1.jsx, src/components/User/Step2.jsx, src/components/User/Step3.jsx, src/pages/User/Login.jsx
=> [FEAT] 네이버,구글로그인 기능 추가, 컴포넌트명 변경

package-lock.json, package.json, src/App.jsx, src/mock/Calendar/calender_schedules.json, src/mock/Calendar/event.json, src/pages/Calender/Calendar.jsx, src/pages/Calender/Calender.jsx
=> [FEAT] 캘린더 컴포넌트 렌더링

src/App.jsx, src/components/PetSta/VideoPlayer.jsx
=> [FIX] Cal import 안된거 수정

src/App.jsx, src/css/Admin.css
=> [FIX] css 파일 충돌 수정

src/App.jsx, src/components/Global/Header.jsx, src/components/PetSta/PhotoDetail.jsx, src/components/PetSta/PhotoPost.jsx, src/components/PetSta/PostBottom.jsx, src/components/PetSta/PostCommentItem.jsx, src/components/PetSta/PostProfile.jsx, src/components/PetSta/PostReplyItem.jsx, src/components/PetSta/VideoDetail.jsx, src/components/PetSta/VideoPost.jsx, src/mock/PetSta/comments.json, src/mock/PetSta/friends.json, src/mock/PetSta/posts.json, src/pages/PetSta/PostCommentsPage.jsx, src/pages/PetSta/PostDetail.jsx
=> [ADD] 댓글페이지 구현

src/App.jsx, src/components/Admin/PetsitterList.jsx, src/mock/Admin/petsitter.json, src/pages/Admin/AdminPetsitterList.jsx
펫시터 리스트 화면 구현
-
-
-
Closes #49
=> [FEAT] 펫시터 리스트 화면

index.html, src/mock/Calendar/event.json, src/pages/Calender/Calendar.jsx
=> [MODITY] 캘린더 일정추가, 상세보기

package-lock.json, package.json, src/App.jsx, src/assets/images/Global/left-arrow-brand.svg, src/components/Global/TitleBar.jsx, src/components/PetSta/PostCommentItem.jsx, src/components/PetSta/PostReplyItem.jsx, src/pages/PetSta/AddPhoto.jsx, src/pages/PetSta/AddVideo.jsx, src/pages/PetSta/PetSta.jsx, src/pages/PetSta/PostCommentsPage.jsx
화면 슬라이드용 framer-motion 패키지 추가
Closes #34
=> [ADD] 댓글페이지 완성

src/context/Context.jsx, src/pages/User/MyModal.jsx, src/pages/User/MyPage.jsx
닉네임 수정 모달, 회원탈퇴 모달
Closes #18 
Closes #18
=> [FEAT] 닉네임 수정/ 회원탈퇴 모달

src/App.jsx, src/components/Admin/Layout.jsx, src/components/Admin/PetSitterApply.jsx, src/components/Admin/PetSitterApplyList.jsx, src/components/Admin/PetSitterDetail.jsx, src/components/Admin/PostDetail.jsx, src/mock/Admin/petsitterApply.json, src/pages/Admin/AdminPetSitterApplyDetail.jsx, src/pages/Admin/AdminPetSitterApplyList.jsx, src/pages/Admin/AdminPetsitterDetail.jsx
=> [FEAT] 펫시터 관리페이지

src/components/Global/TitleBar.jsx
<TitleBar name="사진 업로드" />
요런식으로 써주세요
Closes #57
=> [MODIFY] 타이틀바 bold로 수정

src/App.jsx
- App.jsx 관리자쪽 url 추가
```jsx
<Route path="/petsta/post/comment/:post_id" element={<PostComment />} />
<Route path="/petsta/post/add/photo" element={<AddPhoto />} />
<Route path="/petsta/post/add/video" element={<AddVideo />} />
```
-
-
-
Closes #이슈번호
=> [FIX] App.jsx 관리자쪽 수정

src/App.jsx
- App.jsx에 반려동물 추가/수정 페이지 부재?로 인한 수정
Closes #18
=> [FIX] App.jsx 반련동물쪽 수정

src/App.jsx
=> [FIX] import 중복 수정

.dockerignore, Dockerfile, deployment.yaml
=> [ADD]Jenkins, K8s 연동기능 추가

src/App.jsx, src/components/Admin/AdminContext.jsx, src/components/Admin/Layout.jsx, src/components/Admin/Login.jsx, src/components/Admin/ProtectedAdminRoute.jsx
- 관리자 로그인 스프링부트 연결
- 관리자 페이지 api 수정
-
-
-
Closes #이슈번호
=> [FEAT] 관리자 로그인 부트연결 1차

src/App.jsx, src/components/Reserve/map/ReserveMap.jsx, src/components/Reserve/utils/CustomizedDot.jsx, src/mock/Reserve/reserveList.json, src/pages/Reserve/ReservationDetail.jsx, src/pages/Reserve/ReservationList.jsx
ReserveMap.jsx 수정
1. 목록 -> 상세보기 페이지 URL 파라미터(id) 확인
UI 추가 작업중
Closes #이슈번호
=> [ADD] 예약 목록, 예약 상세 페이지 추가

src/App.jsx
=> [FIX] 라우터 중복 제거

Dockerfile, nginx.conf
=> [FIX] 엔진엑스 설정 Dockerfile에 포함

src/App.jsx, src/components/Admin/AdminBoardApi.js, src/components/Admin/AdminContext.jsx, src/components/Admin/AdminLayout.jsx, src/components/Admin/DashBoard.jsx, src/components/Admin/ProtectedAdminRoute.jsx, src/components/Admin/ProtectedAdminRoute2.jsx, src/pages/Admin/TestPage.jsx
- 게시글 관리 페이지 안보이는 문제 수정
-
-
-
- #119 
Closes #119
=> [FIX] 게시글 관리 페이지 화면 수정

nginx.conf, vite.config.js
=> [FIX] nginx 수정

src/components/PetSta/AddPhotoDetail.jsx, src/components/PetSta/AddPhotoSelect.jsx, src/pages/PetSta/AddPhoto.jsx, src/services/axiosInstance.js, src/services/petstaService.js
=> [ADD]서버에 게시물 업로드 구현

nginx.conf, src/components/PetSta/AddPhotoDetail.jsx, src/components/PetSta/PhotoPost.jsx, src/pages/PetSta/PetSta.jsx, src/services/petstaService.js
=> [ADD]펫스타에서 포스트리스트 구현

src/pages/User/MyPage.jsx
-API 통신 추가
-반려동물 삭제 기능 추가
- #18
=> [MODIFY]마이페이지 수정

vite.config.js
=> [FIX] vite.config 들여쓰기

deployment.yaml, nginx.conf
=> [FIX]nginx, deployment 수정

src/components/Admin/AdminBoardApi.js, src/components/Admin/AdminContext.jsx, src/components/Admin/DashBoard.jsx, src/components/Admin/Notice.jsx, src/components/Admin/PostDetail.jsx
=> [FEAT] 공지 작성 1차

src/components/Admin/AdminPetSitterApi.js, src/components/Admin/DashBoard.jsx, src/components/Admin/PetsitterList.jsx
펫시터 목록 페이지 1차 구현
-
-
-
- #143 
Closes #143
=> [FEAT] 펫시터 목록 1차

src/pages/User/AddPet.jsx, src/pages/User/EditPet.jsx, src/pages/User/MyPage.jsx
=> [Modify]2차 마이페이지 조회/수정/추가/삭제

src/components/Admin/AdminBoardApi.js, src/components/Admin/AdminContext.jsx, src/components/Admin/AdminLayout.jsx, src/components/Admin/AdminPetSitterApi.js, src/components/Admin/DashBoard.jsx, src/components/Admin/PetSitterDetail.jsx, src/components/Admin/PetsitterList.jsx, src/components/Admin/ProtectedAdminRoute.jsx
펫시터 목록 상세보기 페이지 구현
- 필요없는 로그들 주석처리
-
-
- #149 
Closes #149
=> [FEAT] 펫시터 목록 상세보기

src/App.jsx, src/components/Admin/AdminPetSitterApi.js, src/components/Admin/Layout.jsx, src/components/Admin/PetSitterApply.jsx, src/components/Admin/PetSitterApplyList.jsx, src/components/Admin/PetSitterDetail.jsx
펫시터 신청목록/상세보기 구현
- applyAt 이 null인 펫시터만 전송
- #155 
Closes #155
=> [FEAT] 펫시터 신청목록/상세보기 구현

src/components/PetSta/Post/PostCommentItem.jsx, src/pages/PetSta/PostCommentsPage.jsx, src/services/petstaService.js
=> [ADD]댓글 기능 구현

src/App.jsx, src/components/Global/Header.jsx, src/components/User/ProtectedRoute.jsx, src/components/User/UserContext.jsx
=> [MODIFY] 불필요코드 제거

src/pages/User/EditPet.jsx, src/pages/User/MyModal.jsx, src/pages/User/MyPage.jsx
=> [Modify] 마이페이지 경로 변경 및 수정쪽 정보 불러오기 수정

src/components/Admin/PetSitterApply.jsx, src/components/Admin/PetSitterDetail.jsx
펫시터 승인/반려/삭제 구현
-
-
-
-
- #150 
Closes #150
=> [FEAT] 펫시터 승인/반려/삭제 구현

src/components/PetMeeting/PetCard.jsx, src/components/PetMeeting/PetProfiles.jsx
거리순으로 펫 친구 불러오고 펫 카드에 거리 표기
Closes #166
=> [FIX] 친구 불러오기 거리순으로 정렬

src/components/User/OAuth2Success.jsx, src/components/User/RegisterContext.jsx
=> [FIX] 회원가입 context, axios 리팩토링

src/App.jsx, src/components/Admin/PetSitterApplyList.jsx, src/components/Admin/PetsitterList.jsx
게시판/펫시터 검색 기능 구현
App.jsx 경로 변경 수정
<Route path="petsitter/apply" element={<AdminPetSitterApplyList />} />
<Route path="petsitter/apply/:id" element={<AdminPetSitterApplyDetail />} />
<Route path="petsitter/pending" element={<AdminPetSitterApplyList />} />
<Route path="petsitter/pending/:id" element={<AdminPetSitterApplyDetail />} />
-
-
-
- #171 
Closes #171
=> [FEAT] 게시판/펫시터 검색 기능 구현

src/pages/Sitter/PetSitterRegister.jsx, src/pages/User/MyPage.jsx, src/pages/User/PetSitterQuitModal.jsx
- 그만두기 가능, 펫시터 신청 시 ui 변경됨
Closes #177
=> [MODIFY] 1차 구현 마이페이지 펫시터 신청 및 그만두기 

src/components/User/MyPage.jsx, src/components/User/OAuth2Success.jsx, src/components/User/ProtectedRoute.jsx, src/components/User/RegisterContext.jsx, src/components/User/Step3.jsx, src/components/User/Step4.jsx, src/services/authService.js
=> [FIX] 회원가입 API 호출방식 수정

src/components/PetMeeting/PetImgSlide.jsx, src/pages/PetMeeting/PetDetails.jsx, src/services/petService.js, src/services/petmeetingService.js
=> [FEAT] 반려동물 상세정보 조회 요청

src/components/Admin/AdminBoardApi.js, src/components/Admin/AdminContext.jsx, src/components/Admin/AdminFacilityApi.js, src/components/Admin/AdminHeader.jsx, src/components/Admin/DashBoard.jsx, src/components/Admin/FacilityList.jsx, src/components/Admin/PetSitterApplyList.jsx, src/components/Admin/PetsitterList.jsx
관리자 페이지 전체적으로 수정
- 검색/필터 분리
-
-
-
- #175 
Closes #175
=> [FIX] 관리자 페이지 전체적으로 수정

src/components/PetSta/FollowBox.jsx, src/components/PetSta/FollowList.jsx, src/components/PetSta/FriendIcon.jsx, src/components/PetSta/FriendList.jsx, src/components/PetSta/MyProfile.jsx, src/components/PetSta/Post/PhotoPost.jsx, src/components/PetSta/Post/PostCommentItem.jsx, src/components/PetSta/Post/PostProfile.jsx, src/components/PetSta/Post/PostReplyItem.jsx, src/components/PetSta/Post/VideoPost.jsx, src/components/PetSta/UserIcon.jsx, src/components/PetSta/UserProfile.jsx, src/pages/PetSta/FollowersTab.jsx, src/pages/PetSta/PetSta.jsx, src/services/petstaService.js
=> [ADD]스토리상태 구현

src/components/Sitter/common/OptionCheckboxGroup.jsx, src/components/Sitter/common/StepButtons.jsx, src/components/Sitter/common/StepProgress.jsx, src/components/Sitter/steps/AgeSelectionStep.jsx, src/components/Sitter/steps/CommentStep.jsx, src/components/Sitter/steps/CompletionStep.jsx, src/components/Sitter/steps/ExperienceStep.jsx, src/components/Sitter/steps/HousingTypeStep.jsx, src/components/Sitter/steps/PetCountStep.jsx, src/components/Sitter/steps/PetOwnershipStep.jsx, src/components/Sitter/steps/PetTypeStep.jsx, src/components/Sitter/steps/ProfileUploadStep.jsx, src/components/Sitter/utils/petSitterUtils.js, src/components/User/Profile/PetListSection.jsx, src/components/User/Profile/PetSitterSection.jsx, src/components/User/Profile/UserProfileSection.jsx, src/pages/Sitter/PetSitterFinder.jsx, src/pages/Sitter/PetSitterRegister.jsx, src/pages/User/MyPage.jsx, src/pages/User/PetSitterQuitModal.jsx
- 마이페이지 컴포넌트 분리 
- 펫시터 신청 분리
- 승인중 ui 변경
Closes #18
=> [MODIFY] 마이페이지 수정 및 펫시터 승인 대기중

src/components/Admin/AdminFacilityApi.js, src/components/Admin/DashBoard.jsx, src/components/Admin/FacilityAdd.jsx, src/components/Admin/FacilityDetail.jsx, src/components/Admin/PetSitterApply.jsx, src/components/Admin/PetSitterDetail.jsx, src/components/Admin/PostDetail.jsx
업체 등록 페이지 1차
-
-
-
- #194 
Closes #194
=> [FEAT] 업체등록 페이지 1차

src/components/Board/AnnounceContainer.jsx, src/components/Board/AnnounceSlider.jsx, src/components/Board/DropdownBoard.jsx, src/components/Board/PostCard.jsx, src/components/Board/SearchBar.jsx, src/components/Board/SelectBoardAndSearch.jsx, src/components/Board/UpdateFile.jsx, src/components/Global/Loading.jsx, src/context/Context.jsx, src/mock/Board/postData.json, src/pages/Board/Announce.jsx, src/pages/Board/Board.jsx, src/pages/Board/PostSave.jsx, src/pages/PetMeeting/PetDetails.jsx, src/services/announceService.js, src/services/boardService.js
=> [FEAT]게시판 API 요청 구현

src/components/Calender/CalendarContext.jsx, src/components/Calender/CalendarRendering.jsx, src/components/Calender/RenderButtonGroup.jsx, src/components/Calender/RenderCard.jsx, src/components/Calender/RenderMapAddress.jsx, src/components/Calender/ScheduleFormCard.jsx, src/pages/Calender/Cal.jsx, src/services/calendarService.js
=> [FEAT] 일정 CRUD, 이벤트 조회, 캘린더 일정추가 버튼 위치 수정 및 업데이트 즉시 반영

src/services/axiosInstance.js
=> [MODIFY] 클라우드 설정 용 테스트

src/services/axiosInstance.js
=> [MODIFY] 원복

src/components/Admin/FacilityDetail.jsx, src/components/Admin/ImageSlider.jsx
업체 상세보기 이미지 리스트 추가
대표이미지 -> 이미지 리스트로 변경
-
-
-
- #207 
Closes #207
=> [FEAT] 업체 상세보기 이미지 리스트

src/components/Sitter/utils/petSitterUtils.js, src/components/User/Profile/PetSitterSection.jsx, src/pages/Sitter/PetSitterRegister.jsx, src/pages/User/MyPage.jsx
=> [MODIFY]마이페이지 펫시터 부분 ui 변경

package-lock.json, src/components/Chat/ChatItem.jsx, src/components/Chat/ChatList.jsx, src/components/Chat/ChatRoom.jsx, src/components/Global/Header.jsx, src/components/PetMeeting/ConfigBtn.jsx, src/components/PetMeeting/FindFriendConfigBtns.jsx, src/components/PetMeeting/MainPageHeader.jsx, src/components/PetMeeting/PetCard.jsx, src/components/PetMeeting/PetMeetingModals.jsx, src/components/PetMeeting/PetMeetingViewSwitch.jsx, src/components/PetMeeting/PetRegister.jsx, src/components/PetMeeting/Scheduler.jsx, src/components/PetSta/FollowList.jsx, src/components/PetSta/MyProfile.jsx, src/components/PetSta/Post/PhotoDetail.jsx, src/context/Context.jsx, src/context/PetMeetingContext.jsx, src/pages/PetMeeting/PetDetails.jsx, src/services/chatService.js
=> [ADD]매칭 기능 구현

src/components/Global/Header.jsx, src/components/User/Profile/ProfileImageEditModal.jsx, src/components/User/Profile/UserProfileSection.jsx, src/pages/Sitter/PetSitterRegister.jsx, src/pages/User/AddPet.jsx, src/pages/User/EditPet.jsx, src/pages/User/MyPage.jsx
-  axiosInstance를 활용해 인증·보안·환경설정 자동
Closes #214
=> [MODIFY]/services/axiosInstance.js에 있는걸로 변경

src/App.jsx, src/components/Sitter/PetSitterResults.jsx, src/pages/Sitter/PetSitterDetail.jsx, src/pages/Sitter/PetSitterFinder.jsx, src/services/petSitterService.js
- 조건 검색 결과(filteredPetsitters)를 기반으로 렌더링
- 결과 없음 시 → 모든 펫시터 보기 버튼 표시
- 버튼 클릭 시 → getAllApprovedPetSitters 호출해서 전체 목록 불러오기
- 각 펫시터 카드는 onClick 시 상세 페이지(/petsitter/:id)로 이동
Closes #90
=> [MODIFY]펫시터 목록 찾기

package-lock.json, src/components/User/ProtectedRoute.jsx, src/services/authService.js
=> [MODIFY] 토큰 갱신 업데이트

src/App.jsx, src/pages/User/BoardBookmarks.jsx, src/pages/User/Bookmark.jsx, src/pages/User/PetstaBookmarks.jsx, src/services/BookmarkService.js
- PetstaBookmarks 및 BoardBookmarks 컴포넌트 이미지 로딩 문제 해결
- boardTypeMap에서 불필요한 "기타" 옵션 제거
- mock 제거
Closes #102
=> [MODIFY] 북마크 페이지

src/components/Global/darkModal.jsx, src/components/User/PetSitterQuitModal.jsx, src/components/User/Profile/PetListSection.jsx, src/components/User/Profile/ProfileImageEditModal.jsx, src/components/User/Profile/UserProfileSection.jsx, src/pages/User/AddPet.jsx, src/pages/User/EditPet.jsx, src/pages/User/MyModal.jsx, src/pages/User/MyPage.jsx
- 마이페이지 반려동물 이미지 관련 문제 수정
- darkmodal 만들어서 마이페이지 쪽 모달 적용
Closes #18
=> [MODIFY] 마이페이지 이미지,모달 수정

src/components/Board/CommentCard.jsx, src/components/Board/DeletePostModal.jsx, src/components/Board/PostTitleBar.jsx, src/components/Board/UploadFiles.jsx, src/components/Board/WriteCommentBar.jsx, src/components/Global/InfoModal.jsx, src/pages/Board/Board.jsx, src/pages/Board/PostDetails.jsx, src/pages/Board/PostSave.jsx, src/pages/PetMeeting/PetDetails.jsx, src/services/boardService.js
=> [FEAT] 게시글 추가 삭제 수정

src/App.jsx
=> [FIX] App.jsx 에 오타 수정

src/App.jsx
=> [FIX] 클라우드 실행

src/pages/Notification/Notification.jsx, src/services/notificationService.js
=> [FIX] 알람 리얼 정상화

src/pages/User/EditPet.jsx
- 이미지 변경사항 적용
- 몸무게 (number -> text)
- 이미지 슬라이드 변경
- 생일 현재시까지만 가능
Closes #18
=> [FIX]반려동물 수정

src/components/Chat/ChatRoom.jsx, src/components/Sitter/PetSitterSurvey.jsx, src/pages/Sitter/PetSitterDetail.jsx, src/pages/Sitter/PetSitterFinder.jsx
-  임보 구하기 이전 버튼 추가
- 임보 구하기 채팅방 추가
Closes #90
=> [FEAT] 임보구하기 기능 추가

src/pages/Sitter/PetSitterRegister.jsx
- 스낵바 위치 변경
- 키우고 있지 않습니다 -> 펫시터를 해보신 경험이 있나요
Closes #50
=> [MODIFY] 펫시터 신청 로직 변경

src/pages/Sitter/PetSitterRegister.jsx
=> [MODIFY]펫시터 신청 오타

src/App.jsx, src/pages/User/Bookmark.jsx, src/pages/User/MyPosts.jsx, src/services/myPostsService.js
- 북마크 쪽 내 게시물 보기 추가
Closes #102
=> [FEAT]북마크 쪽 내 게시물 보기

src/components/PetSta/Post/PhotoPost.jsx, src/components/PetSta/Post/PostBottom.jsx, src/components/PetSta/Post/PostCommentItem.jsx, src/pages/Notification/Notification.jsx
=> [FIX]컴퓨터 시간 기준으로 수정

src/App.jsx, src/components/Chat/ChatList.jsx, src/components/Chat/ChatRoom.jsx, src/components/User/ProtectedRoute.jsx, src/context/Context.jsx, src/pages/Notification/Notification.jsx
-프론트에서 userid,메세지 가져옴
-알람 모든 상황에서 뜨도록(안뜨면 버그임;;)
=> [MODIFY] 채팅알람 기능개선

src/App.jsx, src/pages/Sitter/PetSitterFinder.jsx, src/pages/User/MyModal.jsx, src/pages/User/MyPage.jsx, src/pages/User/WithdrawalCompletePage.jsx
=> [FEAT] 임보구해요 새로고침 및 회원탈퇴 추가

src/components/User/Step1.jsx, src/components/User/Step2.jsx, src/components/User/Step3.jsx, src/pages/User/WithdrawalCompletePage.jsx
=> [MODIFY] 회원가입 유효성 snackbar사용

src/components/Calender/CalendarRendering.jsx, src/components/User/ProtectedRoute.jsx, src/components/User/RegisterContext.jsx, src/components/User/Step1.jsx, src/components/User/Step2.jsx, src/components/User/Step3.jsx, src/components/User/Step4.jsx, src/css/App.css, src/services/authService.js, src/theme/theme.js
=> [MODIFY] 회원가입 유효성 검사 및 응답객체 설정

src/components/User/ProtectedRoute.jsx, src/services/authService.js
=> [MODIFY] 알람토큰DB수정

src/components/Global/DarkModal.jsx, src/components/Sitter/common/OptionCheckboxGroup.jsx, src/components/Sitter/common/StepButtons.jsx, src/components/Sitter/common/StepProgress.jsx, src/components/Sitter/steps/AgeSelectionStep.jsx, src/components/Sitter/steps/CommentStep.jsx, src/components/Sitter/steps/CompletionStep.jsx, src/components/Sitter/steps/ExperienceStep.jsx, src/components/Sitter/steps/HousingTypeStep.jsx, src/components/Sitter/steps/PetCountStep.jsx, src/components/Sitter/steps/PetOwnershipStep.jsx, src/components/Sitter/steps/PetTypeStep.jsx, src/components/Sitter/steps/ProfileUploadStep.jsx, src/components/Sitter/utils/petSitterUtils.js, src/components/User/Profile/PetListSection.jsx, src/components/User/Profile/PetSitterSection.jsx, src/components/User/Profile/ProfileImageEditModal.jsx, src/components/User/Profile/UserProfileSection.jsx, src/constants/petTypes.js, src/pages/Sitter/PetSitterFinder.jsx, src/pages/User/AddPet.jsx, src/pages/User/EditPet.jsx
=> [MODIFY] 디자인 변경

public/firebase-messaging-sw.js, src/components/User/ProtectedRoute.jsx
=> [MODIFY] rabbitmq 수정

src/pages/Sitter/PetSitterFinder.jsx
=> [MODIFY] 새로고침 버튼 위치 조정

package-lock.json, package.json, src/App.jsx, src/components/Board/CommentCard.jsx, src/components/Board/DropdownPostBtns.jsx, src/components/Board/ImgSlider.jsx, src/components/Board/PostTitleBar.jsx, src/components/Board/UsedMarketBar.jsx, src/components/Global/GlobalSnackbar.jsx, src/components/PetMeeting/LocationConfig.jsx, src/components/PetMeeting/LocationConfigBtns.jsx, src/components/PetMeeting/PetMeetingModals.jsx, src/components/PetMeeting/SelectPetDropdown.jsx, src/context/Context.jsx, src/hook/useTimeAgo.js, src/pages/Board/PostDetails.jsx, src/pages/Board/PostSave.jsx, src/pages/PetMeeting/PetDetails.jsx, src/services/boardService.js
=> [FIX] 게시판, 펫미팅 버그 수정

public/mainifest.json
=> [MODIFY] manifest.json 추가 테스트

public/firebase-messaging-sw.js
=> [MODIFY] manifest.json 추가 테스트3

src/components/User/ProtectedRoute.jsx
=> [MODIFY] manifest.json 추가 테스트4

src/components/Sitter/PetSitterResults.jsx, src/components/Sitter/steps/CompletionStep.jsx, src/components/Sitter/utils/petSitterUtils.js, src/components/User/Profile/PetSitterSection.jsx, src/pages/Sitter/PetSitterRegister.jsx, src/pages/User/MyPage.jsx
-petSitterUtils.js에 다중 반려동물 타입 처리 함수 
-PetSitterRegister.jsx에서 다중 선택된 반려동물 타입 처리
-PetSitterSection.jsx에서 표시 로직 수정
-MyPage.jsx에 petTypesFormatted 필드 추가
Closes #177
=> [MODIFY] 펫시터 다중 반려동물 타입 기능 수정

src/components/Sitter/PetSitterResults.jsx, src/pages/Sitter/PetSitterDetail.jsx
- PetSitterResults.jsx에서 반려동물과 키우는 수 분리 표시
-  PetSitterDetail.jsx에서 반려동물과 키우는 수 분리 표시
Closes #90
=> [MODIFY] 임보구해요 다중 반려동물로 변경

src/components/Chat/ChatRoom.jsx, src/pages/Sitter/PetSitterDetail.jsx
=> [MODIFY] 펫시터 채팅방 여러동물로 변경

public/firebase-messaging-sw.js
=> [MODIFY] 파이어베이스 버젼 통일

src/components/User/ProtectedRoute.jsx
=> [FIX] 보안정책 설정

src/components/Reserve/map/ReserveMap.jsx, src/pages/Reserve/ReserveDetail.jsx
=> [FIX] 시설 상세보기 지도 참조값 변경(address -> lat, lng)

src/components/Calender/CalendarContext.jsx, src/components/Calender/CalendarRendering.jsx, src/components/Calender/DaumPost.jsx, src/components/Calender/DaumPost2.jsx, src/components/Calender/ScheduleFormCard.jsx
=> [MODIFY] 캘린더 UI변경, 재렌더링, 유효성 검사

src/App.jsx, src/pages/Reserve/DateTimeSelector.jsx, src/pages/Reserve/Reservation.jsx, src/pages/Reserve/Reserve.jsx, src/pages/Reserve/ReserveDetail.jsx, src/services/reserveService.js
=> [ADD]결제하기 구현

src/pages/Reserve/ReservationList.jsx, src/services/reserveService.js
=> [ADD] 내 예약 목록 구현

src/pages/Reserve/ReservationList.jsx, src/pages/Reserve/ReserveDetail.jsx
시설 리스트/상세보기
-
-
-
-
Closes #이슈번호
=> [FIX] 시설 리스트/상세보기

src/components/Chat/ChatRoom.jsx, src/components/Sitter/PetSitterResults.jsx, src/pages/Sitter/PetSitterDetail.jsx
- 펫시터 채팅방 수신자는 문구 안 나오도록 수정
- 펫시터 채팅방 한 개의 문구만 나오도록 수정
- 임보구해요 목록에서 현재 로그인한 사용자 제외 처리
=> [MODIFY] 채팅방 및 임보구해요 수정

src/components/Global/GlobalModal.jsx, src/components/PetSta/Upload/AddVideoDetail.jsx, src/components/PetSta/Upload/AddVideoTrim.jsx, src/pages/Reserve/ReservationDetail.jsx, src/services/reserveService.js
=> [MODIFY] 동영상 업로드 수정

src/components/Sitter/steps/HousingTypeStep.jsx, src/pages/Sitter/PetSitterDetail.jsx, src/pages/Sitter/PetSitterRegister.jsx
- 반려동물을 키우지 않는 펫시터의 경우, "키우는 수" 항목 대신 "반려동물: 키우고 있지 않음"으로 표시
- HousingTypeStep 컴포넌트에서 다중 선택이 아닌 단일 선택만 가능하도록 multiSelect={false}로 변경
Closes  #50
=> [MODIFY] 펫시터 등록 및 상세정보 화면

src/components/Sitter/steps/HousingTypeStep.jsx, src/pages/User/MyModal.jsx
=> [MODIFY] 회원탈퇴 변경

src/components/Calender/CalendarContext.jsx, src/components/Calender/CalendarRendering.jsx, src/components/Calender/RenderCard.jsx, src/services/calendarService.js
=> [FEAT] 캘린더 예약 연동

src/components/Board/SelectBoardAndSearch.jsx, src/components/Board/WriteCommentBar.jsx, src/pages/Board/Board.jsx, src/pages/PetSta/PostCommentsPage.jsx
=> [FIX] 채팅입력창 우측 여백 추가

src/components/Board/CommentCard.jsx, src/pages/Board/PostDetails.jsx
=> [FIX] 댓글 추가 수정 성공 스낵바 제거

public/firebase-messaging-sw.js, src/components/User/ProtectedRoute.jsx
=> [FIX] 알람테스트

public/firebase-messaging-sw.js
=> [FIX] 알림테스트 2

public/firebase-messaging-sw.js, src/components/User/ProtectedRoute.jsx
=> [FIX] 알림테스트3

src/components/Reserve/content/FacilityCards.jsx, src/pages/Reserve/ReserveDetail.jsx
=> [FIX] 시설 리스트 수정

src/components/Reserve/utils/FileUploader.jsx, src/components/Reserve/utils/StarRatingConstructor.jsx, src/pages/Reserve/Review.jsx, src/services/reserveService.js
1. 리뷰 화면 출력 시 서버에 요청한 시설 정보(이름, 사진) 정상 출력 확인
2. 리뷰 작성 후 등록 처리 요청값 서버 확인
Closes #
=> [FIX] 시설 리뷰쓰기 1, 2차

src/components/Global/Header.jsx, src/pages/Notification/Notification.jsx
=> [FIX] 알람 아이콘 크기수정

src/pages/User/MyPage.jsx
=> [MODIFY] 펫시터 그만두기 alert 삭제

src/components/Chat/ChatRoom.jsx, src/components/Payment/PaymentInterface.jsx, src/components/Payment/hooks/useFilterOptions.jsx, src/components/PetSta/Post/VideoDetail.jsx, src/components/PetSta/Upload/AddPhotoDetail.jsx, src/components/PetSta/Upload/AddVideoDetail.jsx, src/css/App.css, src/pages/Board/PostDetails.jsx, src/pages/PetSta/EditPhotoDetail.jsx, src/pages/PetSta/EditVideoDetail.jsx, src/pages/Reserve/ReserveDetail.jsx, src/services/paymentService.js
=> [ADD]결재내역 구현

src/App.jsx, src/components/Admin/NoticeDetail.jsx, src/components/Admin/PetSitterApplyList.jsx, src/components/Admin/PetsitterList.jsx, src/components/Admin/adminNoticeApi.js, src/pages/Admin/AdminNoticeDetail.jsx
=> [FEAT] 공지 상세보기

src/components/User/ProtectedRoute.jsx, src/pages/Notification/FetchRoomsListener.jsx
=> [MODIFY] 채팅방 생성은 프론트에서 알림안뜨게

src/pages/Reserve/ReservationDetail.jsx, src/pages/Reserve/ReservationList.jsx, src/pages/Reserve/ReserveDetail.jsx
=> [FIT] 예약취소 모달로 변경

src/components/Board/DropdownBoardItem.jsx
=> [FIT] 게시판 타입 선택 커서 포인터로 변경

src/components/Admin/PetSitterDetail.jsx
펫시터 삭제를 펫시터 정지로 수정
Closes #이슈번호
=> [CHORE] 펫시터 삭제를 펫시터 정지로 수정

src/components/Calender/CalendarContext.jsx, src/components/Calender/CalendarRendering.jsx, src/components/Calender/ScheduleFormCard.jsx, src/context/Context.jsx, src/pages/Reserve/ReservationDetail.jsx
=> [MODIFY] 캘린더 글로벌 스낵바 사용

src/pages/Sitter/PetSitterFinder.jsx
=> [MODIFY] 임보구해요 새로고침 버튼 위치 수정

src/pages/Sitter/PetSitterRegister.jsx
=> [MODIFY] 펫시터 pending 수정 사진 쪽 변경

src/pages/Reserve/ReserveDetail.jsx
이용자 평점 별 갯수 로직 변경, 점수 비율 그래프 비율 수정
1. UI 정상 출력 확인
=> [FIX] 예약 상세 평점, 점수 비율 UI 수정

src/pages/Reserve/ReservationDetail.jsx, src/pages/Reserve/ReservationList.jsx, src/pages/Reserve/ReserveDetail.jsx, src/pages/Reserve/Review.jsx, src/services/reserveService.js
=> [FIX] 1예약당 1리뷰만 가능하게 수정

src/components/Calender/CalendarContext.jsx, src/components/Calender/CalendarRendering.jsx
=> [FIX] 캘린더 이벤트, 예약 날짜 출력 수정

src/components/Reserve/content/ListContent.jsx, src/pages/Reserve/Reservation.jsx, src/pages/Reserve/ReservationList.jsx, src/pages/Reserve/ReserveDetail.jsx, src/pages/Reserve/Review.jsx
=> [FIX] 예약 목록 최신순으로 반환

src/components/Reserve/content/FacilityCards.jsx, src/pages/Reserve/DateTimeSelector.jsx, src/pages/Reserve/ReserveDetail.jsx, src/pages/Reserve/ReviewCardItem.jsx, src/pages/Reserve/ReviewDropDown.jsx, src/services/reserveService.js
=> [FEAT] 리뷰 수정, 삭제 기능 구현 1, 2차

src/constants/petTypes.js, src/pages/User/AddPet.jsx, src/pages/User/EditPet.jsx
=> [MODIFY] 새->앵무새

src/components/Payment/FilterSection.jsx, src/components/Payment/PaymentHistoryItem.jsx, src/components/Payment/PaymentInterface.jsx, src/pages/Reserve/ReservationDetail.jsx, src/services/paymentService.js
=> [FIX] 날짜값 결제일에서 체크인 날짜로 수정

src/components/Global/ImgSlider.jsx, src/pages/Board/Announce.jsx, src/pages/Board/PostDetails.jsx, src/pages/Reserve/ReserveDetail.jsx
=> [FIX] 편의시설 상세 이미지 슬라이더 적용

src/components/Global/DarkModal.jsx, src/components/Sitter/common/StepButtons.jsx, src/components/Sitter/steps/CompletionStep.jsx, src/components/Sitter/steps/ProfileUploadStep.jsx, src/components/User/PetSitterQuitModal.jsx, src/components/User/Profile/PetSitterSection.jsx, src/components/User/Profile/ProfileImageEditModal.jsx, src/pages/Sitter/PetSitterRegister.jsx, src/pages/User/MyModal.jsx, src/pages/User/MyPage.jsx
=> [MODIFY] 수정

src/components/Admin/FacilityAdd.jsx, src/components/Calender/CalendarContext.jsx, src/components/Calender/CalendarRendering.jsx, src/components/Calender/RenderCard.jsx, src/components/User/Step1.jsx
=> [FIX] 버그 수정

src/components/Payment/PaymentHistoryItem.jsx
=> [FIX] 이미지 고정크기로 조정

src/components/Sitter/steps/ProfileUploadStep.jsx, src/components/User/Profile/PetSitterSection.jsx
=> [MODIFY] ui수정

src/components/Payment/FilterSection.jsx, src/pages/Notification/Notification.jsx
=> [fix] 결제내역수정

src/components/Chat/ChatList.jsx, src/components/PetSta/FriendIcon.jsx, src/pages/PetSta/PostCommentsPage.jsx
=> 댓글이미지, 채팅창 수정

src/components/Reserve/content/FacilityCards.jsx, src/pages/Reserve/ReserveDetail.jsx, src/pages/Reserve/ReviewCardItem.jsx, src/pages/Reserve/StarRating.jsx
=> [FIX] 리뷰 작성, 수정, 삭제 성공 메시지 모달 삭제

src/components/Payment/PaymentHistoryItem.jsx, src/components/Reserve/filter/ReviewFilter.jsx, src/components/Sitter/steps/CommentStep.jsx, src/pages/Reserve/ReserveDetail.jsx, src/services/reserveService.js
=> [ADD] 이용자 리뷰 필터 추가

src/components/Board/CommentCard.jsx
=> [FIX] 삭제된 유저 멘션 수정

src/components/Sitter/common/StepProgress.jsx
=> [MODIFY]에너지바 에니메이션 적용 수정

src/components/Payment/FilterSection.jsx, src/components/Payment/PaymentHistoryItem.jsx, src/components/Payment/PaymentInterface.jsx
=> [FIX] 결제내역 CSS 수정

src/components/Reserve/content/FacilityCards.jsx, src/pages/Reserve/Reserve.jsx, src/pages/Reserve/ReserveDetail.jsx
=> [FIX] 시설 리스트, 상세보기 별점 UI 개같이 부활

src/pages/User/BoardBookmarks.jsx, src/pages/User/MyPosts.jsx, src/pages/User/PetstaBookmarks.jsx
=> [MODIFY]맨위로 가도록

src/components/Sitter/steps/ProfileUploadStep.jsx, src/components/User/Profile/ProfileImageEditModal.jsx
=> [MODIFY] 프로필이미지 수정

src/components/Board/CommentCard.jsx, src/pages/Reserve/ReservationDetail.jsx, src/pages/Reserve/Review.jsx
=> [FIX] 리뷰페이지 잘못된 접근 차단

src/pages/Reserve/Review.jsx
=> [REFACTOR] 리뷰 잘못된 접근 리팩토링

src/pages/Reserve/DateTimeSelector.jsx, src/pages/Reserve/ReserveDetail.jsx
=> [MODIFY]편의시설 상세보기

src/components/User/DebugInfo.jsx, src/components/User/RegisterContext.jsx, src/components/User/Step3.jsx, src/components/User/Step4.jsx, src/pages/Reserve/Reservation.jsx
=> [FIX] 회원가입 관련 수정(동물하나만 등록)

src/components/Sitter/PetSitterResults.jsx, src/components/Sitter/PetSitterSurvey.jsx, src/pages/Sitter/PetSitterDetail.jsx, src/pages/Sitter/PetSitterFinder.jsx
=> [MODIFY]펫시터 찾기 기능 alert를 GlobalSnackbar로 변경

src/pages/Reserve/Review.jsx, src/pages/Reserve/ReviewCardItem.jsx
=> [FIX] 리뷰 페이지 불필요한 모달 제거

src/pages/User/MyPage.jsx
=> [MODIFY] alert변경

src/components/Payment/PaymentHistoryItem.jsx
=> [FIX] 결제내역 카드 수정

src/components/Reserve/utils/FileUploader.jsx, src/components/Reserve/utils/StarRatingConstructor.jsx, src/pages/Reserve/DateTimeSelector.jsx, src/pages/Reserve/ReservationDetail.jsx, src/pages/Reserve/Review.jsx, src/pages/Reserve/ReviewCardItem.jsx
=> [FIX] 리뷰 작성화면 UI 수정 2차

src/components/Payment/PaymentHistoryItem.jsx
=> [FIX] 결제네역 카드 미세조정

src/components/Admin/FacilityList.jsx, src/components/Board/AnnounceContainer.jsx, src/components/Board/PostCard.jsx, src/components/Board/SelectBoardAndSearch.jsx, src/components/Calender/CalendarRendering.jsx, src/components/Chat/ChatList.jsx, src/components/PetSta/Upload/AddPhotoSelect.jsx, src/components/PetSta/Upload/AddVideoSelect.jsx, src/components/User/Profile/PetSitterSection.jsx, src/components/User/Profile/ProfileImageEditModal.jsx, src/components/User/Step4.jsx, src/pages/Board/Board.jsx, src/pages/Board/PostDetails.jsx, src/pages/Board/PostSave.jsx, src/pages/Notification/Notification.jsx, src/pages/Sitter/PetSitterRegister.jsx, src/pages/User/MyPage.jsx
=> [FIX] 버그 수정/css 수정

src/pages/Reserve/DateTimeSelector.jsx
=> [MODIFY] 오늘 날짜에서 지난 시간 안 뜨도록 수정

src/components/Reserve/filter/ReviewFilter.jsx
=> [FIX] 리뷰필터 UI 설정

src/pages/Reserve/ReserveDetail.jsx
=> [FIX] 평균별점 출력 버그 수정

public/firebase-messaging-sw-register.js, public/firebase-messaging-sw.js, public/firebase.js, src/components/Admin/AdminContext.jsx, src/components/Admin/FacilityUpdate.jsx, src/components/Admin/NoticeList.jsx, src/components/Admin/PetSitterApplyList.jsx, src/components/Admin/adminBoardApi.js, src/components/Board/CommentCard.jsx, src/components/Board/DeletePostModal.jsx, src/components/Calender/CalendarContext.jsx, src/components/Calender/CalendarRendering.jsx, src/components/Payment/hooks/useFilterOptions.jsx, src/components/Payment/hooks/usePaymentsData.jsx, src/components/PetMeeting/PetMeetingModals.jsx, src/components/PetMeeting/PetProfiles.jsx, src/components/PetSta/Post/PostCommentItem.jsx, src/components/PetSta/UserLayout.jsx, src/components/PetSta/UserProfile.jsx, src/components/Reserve/content/ListContent.jsx, src/components/Sitter/PetSitterResults.jsx, src/components/User/Profile/PetSitterSection.jsx, src/hook/Reserve/useGeolocation.js, src/pages/Reserve/ReservationDetail.jsx, src/services/calendarService.js
=> [CHORE] 로그제거

src/components/Reserve/filter/ReviewFilter.jsx
=> [FIX] exclusive 원복

src/components/Reserve/content/FacilityCards.jsx
=> [FIX] 전화번호 표기형식 수정 (02123 -> 02-123)

src/components/Payment/PaymentHistoryItem.jsx
=> [FIX] 결제내역 카드 미세조정

src/components/Reserve/content/ListContent.jsx, src/pages/Reserve/Reserve.jsx, src/pages/Reserve/ReserveDetail.jsx
=> [FIX] 편의시설 평균별점 업체리스트에 바로 적용 안되는 버그 수정 

src/components/Admin/FacilityList.jsx, src/components/Admin/PostDetail.jsx
=> [FIX] 버그수정

src/components/Reserve/content/ListContent.jsx
=> 에러 확인용 콘솔로그 추가

src/components/Payment/PaymentHistoryItem.jsx
=> [FIX] 결제내역카드 미세조정

src/components/Board/PostCard.jsx
=> [FIX] 중고게시판 가격/상태 추가

src/components/Board/UsedMarketBar.jsx, src/pages/Board/PostDetails.jsx, src/pages/Board/PostSave.jsx, src/services/boardService.js
=> [FEAT] 거래 완료 기능 추가

src/components/Board/UsedMarketBar.jsx
=> [FIX] 가격 0원 문구 무료나눔으로 수정

src/components/User/Step1.jsx
=> [CHORE] 회원가입 문구 수정

src/components/Board/CommentCard.jsx, src/pages/Board/PostDetails.jsx
=> [FIX] 댓글 삭제 시 댓글 갯수 카운트 ui 바로 반영

src/components/Global/BottomButton.jsx
=> [CHORE] 푸터 수정

src/components/Payment/PaymentHistory.jsx, src/components/Payment/PaymentHistoryItem.jsx, src/pages/Reserve/ReservationDetail.jsx
=> [FIX] 예약목록 진짜 마지막?

src/components/Reserve/content/FacilityCards.jsx, src/pages/Reserve/ReserveDetail.jsx
=> [FIX] 시설 리스트, 상세정보 연락처 지역번호 포맷 로직 추가

src/components/Calender/RenderCard.jsx
=> [FIX] 캘린더 수정

src/components/User/Step2.jsx, src/components/User/Step3.jsx, src/components/User/Step4.jsx, src/pages/User/EditPet.jsx
=> [FIX] 몸무게, 글자수 제한
